server:
  port: 8083

spring:
  #  max-file-size 表示单个文件的最大允许大小，max-request-size 表示整个请求的最大大小
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: slice
  profiles:
    active: dev
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  datasource:
    url: jdbc:mysql://124.222.236.66:3306/slice
    username: xxx
    password: xxx2807420533
    driver-class-name: com.mysql.cj.jdbc.Driver
  web:
    resources:
      static-locations: file:C:/svs/
#  security:
#    patterns:
#      - /user/get
#      - /user/login



mybatis:
  typeAliasesPackage: com.slice.pojo.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true